import { Lead, Client, Project, Activity, Notification } from '@/types';

// ==========================================
// Mock Leads
// ==========================================
export const mockLeads: Lead[] = [
  {
    id: 'lead-1',
    fullName: 'Aziz Karimov',
    companyName: 'TechStart UZ',
    email: 'aziz@techstart.uz',
    phone: '+998901234567',
    source: 'Landing Page',
    status: 'new',
    firstContactDate: '2026-04-03T10:30:00Z',
    lastContactDate: '2026-04-03T10:30:00Z',
    estimatedBudget: 2000,
    serviceRequested: 'Telegram Bot',
    notes: '',
    inquiryMessage: 'Salom! Telegram bot kerak edi, avtomatik javob beruvchi. Narxlari qancha?',
    submittedAt: '2026-04-03T10:30:00Z',
    unread: true,
    tags: ['telegram', 'bot'],
  },
  {
    id: 'lead-2',
    fullName: 'Maria Petrova',
    companyName: 'GreenFood LLC',
    email: 'maria@greenfood.ru',
    phone: '+79161234567',
    source: 'Landing Page',
    status: 'contacted',
    firstContactDate: '2026-03-28T14:00:00Z',
    lastContactDate: '2026-04-01T09:00:00Z',
    estimatedBudget: 5000,
    serviceRequested: 'Web Application',
    notes: 'Needs e-commerce features, delivery tracking',
    inquiryMessage: 'We need a website with online ordering system for our organic food delivery.',
    submittedAt: '2026-03-28T14:00:00Z',
    unread: false,
    tags: ['web', 'ecommerce'],
  },
  {
    id: 'lead-3',
    fullName: 'James Wilson',
    companyName: 'Wilson Consulting',
    email: 'james@wilsonconsulting.com',
    phone: '+14155551234',
    source: 'Referral',
    status: 'qualified',
    firstContactDate: '2026-03-20T08:00:00Z',
    lastContactDate: '2026-03-30T16:00:00Z',
    estimatedBudget: 15000,
    serviceRequested: 'CRM System',
    notes: 'Enterprise client. Needs custom CRM with analytics.',
    inquiryMessage: 'Looking for a custom CRM solution for our consulting firm. Budget is flexible.',
    submittedAt: '2026-03-20T08:00:00Z',
    unread: false,
    tags: ['crm', 'enterprise'],
  },
  {
    id: 'lead-4',
    fullName: 'Dilshod Rahimov',
    companyName: 'FastDelivery',
    email: 'dilshod@fastdelivery.uz',
    phone: '+998933456789',
    source: 'Landing Page',
    status: 'proposal',
    firstContactDate: '2026-03-15T11:00:00Z',
    lastContactDate: '2026-04-02T14:30:00Z',
    estimatedBudget: 8000,
    serviceRequested: 'Mobile App',
    notes: 'Sent proposal on April 2. Waiting for response.',
    inquiryMessage: 'Yetkazib berish xizmati uchun mobil ilova kerak. iOS va Android.',
    submittedAt: '2026-03-15T11:00:00Z',
    unread: false,
    tags: ['mobile', 'delivery'],
  },
  {
    id: 'lead-5',
    fullName: 'Olga Smirnova',
    companyName: '',
    email: 'olga.s@gmail.com',
    phone: '+79031112233',
    source: 'Landing Page',
    status: 'new',
    firstContactDate: '2026-04-03T08:15:00Z',
    lastContactDate: '2026-04-03T08:15:00Z',
    estimatedBudget: 1500,
    serviceRequested: 'Landing Page',
    notes: '',
    inquiryMessage: 'Need a beautiful landing page for my beauty salon. Modern design.',
    submittedAt: '2026-04-03T08:15:00Z',
    unread: true,
    tags: ['landing', 'design'],
  },
  {
    id: 'lead-6',
    fullName: 'Sardor Aliyev',
    companyName: 'AutoParts UZ',
    email: 'sardor@autoparts.uz',
    phone: '+998901112233',
    source: 'Telegram',
    status: 'negotiation',
    firstContactDate: '2026-03-10T09:00:00Z',
    lastContactDate: '2026-04-03T11:00:00Z',
    estimatedBudget: 12000,
    serviceRequested: 'E-commerce Platform',
    notes: 'Negotiating price. Client wants payment in milestones.',
    inquiryMessage: 'Avtomobil ehtiyot qismlari uchun onlayn do\'kon kerak.',
    submittedAt: '2026-03-10T09:00:00Z',
    unread: false,
    tags: ['ecommerce', 'automotive'],
  },
  {
    id: 'lead-7',
    fullName: 'Chen Wei',
    companyName: 'Dragon Import Export',
    email: 'chen@dragonimex.com',
    phone: '+8613912345678',
    source: 'Upwork',
    status: 'won',
    firstContactDate: '2026-02-20T06:00:00Z',
    lastContactDate: '2026-03-25T10:00:00Z',
    estimatedBudget: 20000,
    serviceRequested: 'Business Platform',
    notes: 'Converted to client. Project started.',
    inquiryMessage: 'Need a B2B platform for import/export tracking and invoice management.',
    submittedAt: '2026-02-20T06:00:00Z',
    unread: false,
    tags: ['b2b', 'platform'],
  },
  {
    id: 'lead-8',
    fullName: 'Nodira Yusupova',
    companyName: 'EduTech Academy',
    email: 'nodira@edutech.uz',
    phone: '+998991234567',
    source: 'Landing Page',
    status: 'lost',
    firstContactDate: '2026-02-15T13:00:00Z',
    lastContactDate: '2026-03-05T15:00:00Z',
    estimatedBudget: 3000,
    serviceRequested: 'LMS Platform',
    notes: 'Budget too low for requirements. Suggested simplified version but client chose another vendor.',
    inquiryMessage: 'Online ta\'lim platformasi kerak. Videodarslar va testlar bo\'lishi kerak.',
    submittedAt: '2026-02-15T13:00:00Z',
    unread: false,
    tags: ['education', 'lms'],
  },
];

// ==========================================
// Mock Clients
// ==========================================
export const mockClients: Client[] = [
  {
    id: 'client-1',
    fullName: 'Chen Wei',
    company: 'Dragon Import Export',
    email: 'chen@dragonimex.com',
    phone: '+8613912345678',
    country: 'China',
    city: 'Shanghai',
    preferredContact: 'email',
    status: 'active',
    totalSpent: 8000,
    projectCount: 1,
    registrationDate: '2026-03-25T10:00:00Z',
    notes: 'Key enterprise client. Very responsive.',
    tags: ['enterprise', 'b2b'],
    convertedFromLeadId: 'lead-7',
  },
  {
    id: 'client-2',
    fullName: 'Jasur Toshmatov',
    company: 'Aurelia Grand Hotel',
    email: 'jasur@aureliagrand.uz',
    phone: '+998901234568',
    country: 'Uzbekistan',
    city: 'Tashkent',
    preferredContact: 'telegram',
    status: 'active',
    totalSpent: 4500,
    projectCount: 2,
    registrationDate: '2025-11-10T08:00:00Z',
    notes: 'Long-term client. Hotel website + booking system.',
    tags: ['hospitality', 'website'],
  },
  {
    id: 'client-3',
    fullName: 'Anvar Nazarov',
    company: 'Managerius',
    email: 'anvar@managerius.com',
    phone: '+998933334455',
    country: 'Uzbekistan',
    city: 'Samarkand',
    preferredContact: 'whatsapp',
    status: 'active',
    totalSpent: 6000,
    projectCount: 1,
    registrationDate: '2026-01-15T09:00:00Z',
    notes: 'Private jet charter platform.',
    tags: ['aviation', 'platform'],
  },
  {
    id: 'client-4',
    fullName: 'Dmitry Volkov',
    company: 'CRM Hisob',
    email: 'dmitry@crmhisob.uz',
    phone: '+998945556677',
    country: 'Uzbekistan',
    city: 'Tashkent',
    preferredContact: 'telegram',
    status: 'active',
    totalSpent: 3200,
    projectCount: 1,
    registrationDate: '2026-02-01T10:00:00Z',
    notes: 'Telegram CRM bot project.',
    tags: ['telegram', 'crm'],
  },
  {
    id: 'client-5',
    fullName: 'Sarah Johnson',
    company: 'BrightFuture Inc',
    email: 'sarah@brightfuture.com',
    phone: '+12125551234',
    country: 'USA',
    city: 'New York',
    preferredContact: 'email',
    status: 'inactive',
    totalSpent: 7500,
    projectCount: 2,
    registrationDate: '2025-08-20T14:00:00Z',
    notes: 'Previous client. Completed 2 projects. May return for mobile app.',
    tags: ['international', 'web'],
  },
];

// ==========================================
// Mock Projects
// ==========================================
export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    title: 'Dragon Import B2B Platform',
    clientId: 'client-1',
    clientName: 'Chen Wei',
    serviceType: 'Business Platform',
    description: 'Full B2B import/export tracking platform with invoice management, shipment tracking, and analytics dashboard.',
    status: 'in_progress',
    priority: 'high',
    startDate: '2026-03-28T00:00:00Z',
    deadline: '2026-05-30T00:00:00Z',
    deliveryDate: null,
    price: 20000,
    amountPaid: 8000,
    remainingAmount: 12000,
    paymentStatus: 'partial',
    assignedTo: 'Bobur A.',
    progress: 35,
    requirements: 'User roles, shipment tracking, invoice generation, analytics, multi-language (EN/CN)',
    notes: 'Phase 1: Core platform. Phase 2: Mobile app.',
  },
  {
    id: 'proj-2',
    title: 'Aurelia Grand Hotel Website',
    clientId: 'client-2',
    clientName: 'Jasur Toshmatov',
    serviceType: 'Website',
    description: 'Premium hotel website with booking system, gallery, and contact forms.',
    status: 'completed',
    priority: 'medium',
    startDate: '2025-11-15T00:00:00Z',
    deadline: '2025-12-30T00:00:00Z',
    deliveryDate: '2025-12-28T00:00:00Z',
    price: 3000,
    amountPaid: 3000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    assignedTo: 'Bobur A.',
    progress: 100,
    requirements: 'Responsive design, booking system, multi-language, SEO optimized',
    notes: 'Delivered on time. Client very satisfied.',
  },
  {
    id: 'proj-3',
    title: 'Aurelia Booking System Upgrade',
    clientId: 'client-2',
    clientName: 'Jasur Toshmatov',
    serviceType: 'Web Application',
    description: 'Upgrade booking system with payment integration and admin panel.',
    status: 'in_progress',
    priority: 'medium',
    startDate: '2026-03-01T00:00:00Z',
    deadline: '2026-04-15T00:00:00Z',
    deliveryDate: null,
    price: 2500,
    amountPaid: 1500,
    remainingAmount: 1000,
    paymentStatus: 'partial',
    assignedTo: 'Bobur A.',
    progress: 70,
    requirements: 'Payme/Click integration, admin panel, email confirmations',
    notes: 'Almost done. Testing payment integration.',
  },
  {
    id: 'proj-4',
    title: 'Managerius Charter Platform',
    clientId: 'client-3',
    clientName: 'Anvar Nazarov',
    serviceType: 'Business Platform',
    description: 'Private jet charter and luxury travel booking platform.',
    status: 'review',
    priority: 'high',
    startDate: '2026-01-20T00:00:00Z',
    deadline: '2026-03-30T00:00:00Z',
    deliveryDate: null,
    price: 8000,
    amountPaid: 6000,
    remainingAmount: 2000,
    paymentStatus: 'partial',
    assignedTo: 'Bobur A.',
    progress: 90,
    requirements: 'Flight search, booking, admin panel, CMS for fleet management',
    notes: 'In client review. Minor design adjustments needed.',
  },
  {
    id: 'proj-5',
    title: 'CRM Hisob Telegram Bot',
    clientId: 'client-4',
    clientName: 'Dmitry Volkov',
    serviceType: 'Telegram Bot',
    description: 'Telegram bot for CRM accounting and financial reports management.',
    status: 'completed',
    priority: 'medium',
    startDate: '2026-02-05T00:00:00Z',
    deadline: '2026-03-05T00:00:00Z',
    deliveryDate: '2026-03-03T00:00:00Z',
    price: 3200,
    amountPaid: 3200,
    remainingAmount: 0,
    paymentStatus: 'paid',
    assignedTo: 'Bobur A.',
    progress: 100,
    requirements: 'Invoice tracking, expense reports, monthly summaries, multi-user support',
    notes: 'Delivered ahead of schedule.',
  },
  {
    id: 'proj-6',
    title: 'BrightFuture Corporate Site',
    clientId: 'client-5',
    clientName: 'Sarah Johnson',
    serviceType: 'Website',
    description: 'Corporate website for US-based tech company.',
    status: 'completed',
    priority: 'low',
    startDate: '2025-08-25T00:00:00Z',
    deadline: '2025-10-01T00:00:00Z',
    deliveryDate: '2025-09-28T00:00:00Z',
    price: 4500,
    amountPaid: 4500,
    remainingAmount: 0,
    paymentStatus: 'paid',
    assignedTo: 'Bobur A.',
    progress: 100,
    requirements: 'Modern design, blog, team page, contact form, CMS',
    notes: 'Completed successfully.',
  },
  {
    id: 'proj-7',
    title: 'BrightFuture Dashboard',
    clientId: 'client-5',
    clientName: 'Sarah Johnson',
    serviceType: 'Analytics Dashboard',
    description: 'Internal analytics dashboard for business KPIs.',
    status: 'completed',
    priority: 'medium',
    startDate: '2025-10-10T00:00:00Z',
    deadline: '2025-11-30T00:00:00Z',
    deliveryDate: '2025-11-25T00:00:00Z',
    price: 3000,
    amountPaid: 3000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    assignedTo: 'Bobur A.',
    progress: 100,
    requirements: 'Real-time charts, KPI tracking, export to PDF/Excel',
    notes: 'Client requested additional features later.',
  },
  {
    id: 'proj-8',
    title: 'AutoParts E-Commerce',
    clientId: '',
    clientName: 'Sardor Aliyev (Lead)',
    serviceType: 'E-commerce Platform',
    description: 'Online auto parts store with search, filtering and order management.',
    status: 'planning',
    priority: 'high',
    startDate: '',
    deadline: '2026-06-30T00:00:00Z',
    deliveryDate: null,
    price: 12000,
    amountPaid: 0,
    remainingAmount: 12000,
    paymentStatus: 'unpaid',
    assignedTo: 'TBD',
    progress: 0,
    requirements: 'Product catalog, search with filters, cart, checkout, admin panel',
    notes: 'Pending contract finalization.',
  },
];

// ==========================================
// Mock Activities
// ==========================================
export const mockActivities: Activity[] = [
  {
    id: 'act-1',
    type: 'lead_created',
    entityType: 'lead',
    entityId: 'lead-1',
    entityName: 'Aziz Karimov',
    description: 'New lead submitted from Landing Page',
    createdAt: '2026-04-03T10:30:00Z',
  },
  {
    id: 'act-2',
    type: 'lead_created',
    entityType: 'lead',
    entityId: 'lead-5',
    entityName: 'Olga Smirnova',
    description: 'New lead submitted from Landing Page',
    createdAt: '2026-04-03T08:15:00Z',
  },
  {
    id: 'act-3',
    type: 'payment_received',
    entityType: 'project',
    entityId: 'proj-1',
    entityName: 'Dragon Import B2B Platform',
    description: 'Payment of $4,000 received (2nd milestone)',
    metadata: { amount: '4000' },
    createdAt: '2026-04-02T16:00:00Z',
  },
  {
    id: 'act-4',
    type: 'proposal_sent',
    entityType: 'lead',
    entityId: 'lead-4',
    entityName: 'Dilshod Rahimov',
    description: 'Proposal sent for Mobile App development ($8,000)',
    createdAt: '2026-04-02T14:30:00Z',
  },
  {
    id: 'act-5',
    type: 'project_status_changed',
    entityType: 'project',
    entityId: 'proj-4',
    entityName: 'Managerius Charter Platform',
    description: 'Status changed from In Progress to Review',
    metadata: { from: 'in_progress', to: 'review' },
    createdAt: '2026-04-01T18:00:00Z',
  },
  {
    id: 'act-6',
    type: 'lead_contacted',
    entityType: 'lead',
    entityId: 'lead-6',
    entityName: 'Sardor Aliyev',
    description: 'Follow-up call about e-commerce project pricing',
    createdAt: '2026-04-01T11:00:00Z',
  },
  {
    id: 'act-7',
    type: 'lead_contacted',
    entityType: 'lead',
    entityId: 'lead-2',
    entityName: 'Maria Petrova',
    description: 'Email sent with initial requirements questionnaire',
    createdAt: '2026-04-01T09:00:00Z',
  },
  {
    id: 'act-8',
    type: 'project_status_changed',
    entityType: 'project',
    entityId: 'proj-3',
    entityName: 'Aurelia Booking System Upgrade',
    description: 'Progress updated to 70%',
    createdAt: '2026-03-31T16:00:00Z',
  },
  {
    id: 'act-9',
    type: 'lead_converted',
    entityType: 'lead',
    entityId: 'lead-7',
    entityName: 'Chen Wei',
    description: 'Lead converted to client',
    createdAt: '2026-03-25T10:00:00Z',
  },
  {
    id: 'act-10',
    type: 'client_created',
    entityType: 'client',
    entityId: 'client-1',
    entityName: 'Chen Wei',
    description: 'New client created from lead conversion',
    createdAt: '2026-03-25T10:00:00Z',
  },
  {
    id: 'act-11',
    type: 'project_created',
    entityType: 'project',
    entityId: 'proj-1',
    entityName: 'Dragon Import B2B Platform',
    description: 'New project created: Dragon Import B2B Platform ($20,000)',
    createdAt: '2026-03-28T08:00:00Z',
  },
  {
    id: 'act-12',
    type: 'payment_received',
    entityType: 'project',
    entityId: 'proj-4',
    entityName: 'Managerius Charter Platform',
    description: 'Payment of $3,000 received (2nd installment)',
    metadata: { amount: '3000' },
    createdAt: '2026-03-20T12:00:00Z',
  },
  {
    id: 'act-13',
    type: 'project_completed',
    entityType: 'project',
    entityId: 'proj-5',
    entityName: 'CRM Hisob Telegram Bot',
    description: 'Project completed and delivered',
    createdAt: '2026-03-03T14:00:00Z',
  },
  {
    id: 'act-14',
    type: 'note_added',
    entityType: 'lead',
    entityId: 'lead-3',
    entityName: 'James Wilson',
    description: 'Added note: Enterprise client. Needs custom CRM with analytics.',
    createdAt: '2026-03-22T15:00:00Z',
  },
  {
    id: 'act-15',
    type: 'form_submission',
    entityType: 'lead',
    entityId: 'lead-2',
    entityName: 'Maria Petrova',
    description: 'Contact form submitted from Landing Page',
    createdAt: '2026-03-28T14:00:00Z',
  },
];

// ==========================================
// Mock Notifications
// ==========================================
export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    type: 'new_lead',
    title: 'New Lead',
    message: 'Aziz Karimov submitted a contact form from Landing Page',
    read: false,
    entityType: 'lead',
    entityId: 'lead-1',
    createdAt: '2026-04-03T10:30:00Z',
  },
  {
    id: 'notif-2',
    type: 'new_lead',
    title: 'New Lead',
    message: 'Olga Smirnova submitted a contact form from Landing Page',
    read: false,
    entityType: 'lead',
    entityId: 'lead-5',
    createdAt: '2026-04-03T08:15:00Z',
  },
  {
    id: 'notif-3',
    type: 'payment',
    title: 'Payment Received',
    message: '$4,000 received for Dragon Import B2B Platform',
    read: true,
    entityType: 'project',
    entityId: 'proj-1',
    createdAt: '2026-04-02T16:00:00Z',
  },
  {
    id: 'notif-4',
    type: 'deadline',
    title: 'Deadline Approaching',
    message: 'Aurelia Booking System Upgrade due in 12 days',
    read: false,
    entityType: 'project',
    entityId: 'proj-3',
    createdAt: '2026-04-03T07:00:00Z',
  },
];
